"""ShipStation labels models — auto-generated, do not edit."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

from ._common import (
    AdvancedShipmentOptions,
    AlternativeIdentifier,
    Dimensions,
    InternationalShipmentOptions,
    LabelDownload,
    LabelMessages,
    Link,
    MonetaryValue,
    OptionalLink,
    Package,
    PaginationLink,
    PaperlessDownload,
    Shipment,
    ShipmentItem,
    ShippingAddress,
    ShippingAddressTo,
    Tag,
    TaxIdentifier,
    Weight,
    Weigth,
)
from ..enums import (
    DeliveryConfirmation,
    DisplayScheme,
    InsuranceProvider,
    LabelChargeEvent,
    LabelDownloadType,
    LabelFormat,
    LabelLayout,
    LabelStatus,
    LabelVoidFailureReason,
    OrderSourceName,
    ShipmentStatus,
    TrackingStatus,
    TrackingStatusDetailCode,
    ValidateAddress,
)


class CreateLabelFromRateRequestBody(BaseModel):
    """A purchase label without shipment request body"""

    model_config = ConfigDict(populate_by_name=True)

    validate_address: Optional[ValidateAddress] = None
    label_layout: Optional[LabelLayout] = None
    label_format: Optional[LabelFormat] = None
    label_download_type: Optional[LabelDownloadType] = None
    display_scheme: Optional[DisplayScheme] = None
    """The display format that the label should be shown in."""


class LabelPackage(BaseModel):
    """A package returned in the response from creating a [shipping label]"""

    model_config = ConfigDict(populate_by_name=True)

    weight: Weight
    """The package weight"""
    package_id: Optional[int] = None
    """The shipment package id"""
    package_code: Optional[str] = None
    """The [package type], such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc. The code `package` indicates """
    dimensions: Optional[Dimensions] = None
    """The package dimensions"""
    insured_value: Optional[MonetaryValue] = None
    """The insured value of the package. Requires the `insurance_provider` field of the shipment to be set."""
    tracking_number: Optional[str] = None
    """The tracking number for the package. The format depends on the carrier."""
    label_download: Optional[LabelDownload] = None
    """The label download for the package"""
    form_download: Optional[OptionalLink] = None
    """The form download for any customs that are needed"""
    qr_code_download: Optional[OptionalLink] = None
    """The QR code download for the package"""
    paperless_download: Optional[PaperlessDownload] = None
    """The paperless details which may contain elements like `href`, `instructions` and `handoff_code`."""
    label_messages: Optional[LabelMessages] = None
    external_package_id: Optional[str] = None
    """An external package id."""
    content_description: Optional[str] = None
    """A short description of the package content. Required for shipments moving to, from, and through Mexico."""
    sequence: Optional[int] = None
    """Package sequence"""
    has_label_documents: Optional[bool] = None
    """Whether the package has label documents available for download"""
    has_form_documents: Optional[bool] = None
    """Whether the package has form documents available for download"""
    has_qr_code_documents: Optional[bool] = None
    """Whether the package has QR code documents available for download"""
    has_paperless_label_documents: Optional[bool] = None
    """Whether the package has paperless documents available for download"""


class CreateLabelFromRateResponseBody(BaseModel):
    """A create label from rate response body"""

    model_config = ConfigDict(populate_by_name=True)

    label_id: Optional[str] = None
    """A string that uniquely identifies the label. This ID is generated by ShipStation when the label is created."""
    status: Optional[LabelStatus] = None
    shipment_id: Optional[str] = None
    """The shipment that this label is for. ShipStation can create a shipment for you automatically when you [create a label], """
    external_shipment_id: Optional[str] = None
    """A unique user-defined key to identify a shipment. This can be used to retrieve the shipment. > **Warning:** The `externa"""
    external_order_id: Optional[str] = None
    """ID that the Order Source assigned"""
    shipment: Optional[Shipment] = None
    """The shipment information used to generate the label"""
    ship_date: Optional[str] = None
    """The date that the package was (or will be) shippped. ShipStation will take the day of week into consideration. For examp"""
    created_at: Optional[datetime] = None
    """The date and time that the label was created in ShipStation ."""
    shipment_cost: Optional[MonetaryValue] = None
    """The cost of shipping, delivery confirmation, and other carrier charges. This amount **does not** include insurance costs"""
    insurance_cost: Optional[MonetaryValue] = None
    """The insurance cost for this package. Add this to the `shipment_cost` field to get the total cost."""
    requested_comparison_amount: Optional[MonetaryValue] = None
    """The total shipping cost for the specified comparison_rate_type."""
    tracking_number: Optional[str] = None
    """The tracking number for the package. Tracking number formats vary across carriers."""
    is_return_label: Optional[bool] = None
    """Indicates whether this is a return label. You may also want to set the `rma_number` so you know what is being returned."""
    rma_number: Optional[str] = None
    """An optional Return Merchandise Authorization number. This field is useful for return labels. You can set it to any strin"""
    is_international: Optional[bool] = None
    """Indicates whether this is an international shipment. That is, the originating country and destination country are differ"""
    batch_id: Optional[str] = None
    """If this label was created as part of a [batch], then this is the unique ID of that batch."""
    carrier_id: Optional[str] = None
    """The unique ID of the [carrier account] that was used to create this label"""
    charge_event: Optional[LabelChargeEvent] = None
    """The label charge event."""
    outbound_label_id: Optional[str] = None
    """The `label_id` of the original (outgoing) label that the return label is for. This associates the two labels together, w"""
    service_code: Optional[str] = None
    """The [carrier service] used to ship the package, such as `fedex_ground`, `usps_first_class_mail`, `flat_rate_envelope`, e"""
    test_label: Optional[bool] = None
    """Indicate if this label is being used only for testing purposes. If true, then no charge will be added to your account."""
    package_code: Optional[str] = None
    """The [package type], such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc. The code `package` indicates """
    validate_address: Optional[ValidateAddress] = None
    voided: Optional[bool] = None
    """Indicates whether the label has been [voided]"""
    voided_at: Optional[datetime] = None
    """The date and time that the label was [voided] , or `null` if the label has not been voided"""
    label_download_type: Optional[LabelDownloadType] = None
    label_format: Optional[LabelFormat] = None
    """The file format that you want the label to be in. We recommend `pdf` format because it is supported by all carriers, whe"""
    display_scheme: Optional[DisplayScheme] = None
    """The display format that the label should be shown in."""
    label_layout: Optional[LabelLayout] = None
    """The layout (size) that you want the label to be in. The `label_format` determines which sizes are allowed. `4x6` is supp"""
    trackable: Optional[bool] = None
    """Indicates whether the shipment is trackable, in which case the `tracking_status` field will reflect the current status a"""
    label_image_id: Optional[str] = None
    """The label image resource that was used to create a custom label image."""
    carrier_code: Optional[str] = None
    """The [shipping carrier] who will ship the package, such as `fedex`, `dhl_express`, `stamps_com`, etc."""
    confirmation: Optional[DeliveryConfirmation] = None
    """The type of delivery confirmation that is required for this shipment."""
    tracking_status: Optional[TrackingStatus] = None
    """The current status of the package, such as `in_transit` or `delivered`"""
    label_download: Optional[LabelDownload] = None
    form_download: Optional[Link] = None
    """The link to download the customs form (a.k.a. commercial invoice) for this shipment, if any. Forms are in PDF format. Th"""
    qr_code_download: Optional[OptionalLink] = None
    """The QR code download for the package"""
    paperless_download: Optional[PaperlessDownload] = None
    """The paperless details which may contain elements like `href`, `instructions` and `handoff_code`."""
    insurance_claim: Optional[Link] = None
    """The link to submit an insurance claim for the shipment. This field is null if the shipment is not insured or if the insu"""
    packages: Optional[list[LabelPackage]] = None
    """The label's package(s). > **Note:** Some carriers only allow one package per label. If you attempt to create a multi-pac"""
    alternative_identifiers: Optional[list[AlternativeIdentifier]] = None
    """Additional information some carriers may provide by which to identify a given label in their system."""
    rate_details: Optional[list[dict[str, Any]]] = None
    tracking_url: Optional[str] = None
    """The URL to track the package. This URL is provided by the carrier and is unique to the tracking number."""
    ship_to: Optional[ShippingAddressTo] = None
    """The recipient's mailing address"""


class CreateLabelFromShipmentRequestBody(BaseModel):
    """A purchase label without shipment request body"""

    model_config = ConfigDict(populate_by_name=True)

    validate_address: Optional[ValidateAddress] = None
    label_layout: Optional[LabelLayout] = None
    label_format: Optional[LabelFormat] = None
    label_download_type: Optional[LabelDownloadType] = None
    display_scheme: Optional[DisplayScheme] = None
    """The display format that the label should be shown in."""


class CreateLabelFromShipmentResponseBody(BaseModel):
    """A create label from shipment response body"""

    model_config = ConfigDict(populate_by_name=True)

    label_id: Optional[str] = None
    """A string that uniquely identifies the label. This ID is generated by ShipStation when the label is created."""
    status: Optional[LabelStatus] = None
    shipment_id: Optional[str] = None
    """The shipment that this label is for. ShipStation can create a shipment for you automatically when you [create a label], """
    external_shipment_id: Optional[str] = None
    """A unique user-defined key to identify a shipment. This can be used to retrieve the shipment. > **Warning:** The `externa"""
    external_order_id: Optional[str] = None
    """ID that the Order Source assigned"""
    shipment: Optional[Shipment] = None
    """The shipment information used to generate the label"""
    ship_date: Optional[str] = None
    """The date that the package was (or will be) shippped. ShipStation will take the day of week into consideration. For examp"""
    created_at: Optional[datetime] = None
    """The date and time that the label was created in ShipStation ."""
    shipment_cost: Optional[MonetaryValue] = None
    """The cost of shipping, delivery confirmation, and other carrier charges. This amount **does not** include insurance costs"""
    insurance_cost: Optional[MonetaryValue] = None
    """The insurance cost for this package. Add this to the `shipment_cost` field to get the total cost."""
    requested_comparison_amount: Optional[MonetaryValue] = None
    """The total shipping cost for the specified comparison_rate_type."""
    tracking_number: Optional[str] = None
    """The tracking number for the package. Tracking number formats vary across carriers."""
    is_return_label: Optional[bool] = None
    """Indicates whether this is a return label. You may also want to set the `rma_number` so you know what is being returned."""
    rma_number: Optional[str] = None
    """An optional Return Merchandise Authorization number. This field is useful for return labels. You can set it to any strin"""
    is_international: Optional[bool] = None
    """Indicates whether this is an international shipment. That is, the originating country and destination country are differ"""
    batch_id: Optional[str] = None
    """If this label was created as part of a [batch], then this is the unique ID of that batch."""
    carrier_id: Optional[str] = None
    """The unique ID of the [carrier account] that was used to create this label"""
    charge_event: Optional[LabelChargeEvent] = None
    """The label charge event."""
    outbound_label_id: Optional[str] = None
    """The `label_id` of the original (outgoing) label that the return label is for. This associates the two labels together, w"""
    service_code: Optional[str] = None
    """The [carrier service] used to ship the package, such as `fedex_ground`, `usps_first_class_mail`, `flat_rate_envelope`, e"""
    test_label: Optional[bool] = None
    """Indicate if this label is being used only for testing purposes. If true, then no charge will be added to your account."""
    package_code: Optional[str] = None
    """The [package type], such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc. The code `package` indicates """
    validate_address: Optional[ValidateAddress] = None
    voided: Optional[bool] = None
    """Indicates whether the label has been [voided]"""
    voided_at: Optional[datetime] = None
    """The date and time that the label was [voided] , or `null` if the label has not been voided"""
    label_download_type: Optional[LabelDownloadType] = None
    label_format: Optional[LabelFormat] = None
    """The file format that you want the label to be in. We recommend `pdf` format because it is supported by all carriers, whe"""
    display_scheme: Optional[DisplayScheme] = None
    """The display format that the label should be shown in."""
    label_layout: Optional[LabelLayout] = None
    """The layout (size) that you want the label to be in. The `label_format` determines which sizes are allowed. `4x6` is supp"""
    trackable: Optional[bool] = None
    """Indicates whether the shipment is trackable, in which case the `tracking_status` field will reflect the current status a"""
    label_image_id: Optional[str] = None
    """The label image resource that was used to create a custom label image."""
    carrier_code: Optional[str] = None
    """The [shipping carrier] who will ship the package, such as `fedex`, `dhl_express`, `stamps_com`, etc."""
    confirmation: Optional[DeliveryConfirmation] = None
    """The type of delivery confirmation that is required for this shipment."""
    tracking_status: Optional[TrackingStatus] = None
    """The current status of the package, such as `in_transit` or `delivered`"""
    label_download: Optional[LabelDownload] = None
    form_download: Optional[Link] = None
    """The link to download the customs form (a.k.a. commercial invoice) for this shipment, if any. Forms are in PDF format. Th"""
    qr_code_download: Optional[OptionalLink] = None
    """The QR code download for the package"""
    paperless_download: Optional[PaperlessDownload] = None
    """The paperless details which may contain elements like `href`, `instructions` and `handoff_code`."""
    insurance_claim: Optional[Link] = None
    """The link to submit an insurance claim for the shipment. This field is null if the shipment is not insured or if the insu"""
    packages: Optional[list[LabelPackage]] = None
    """The label's package(s). > **Note:** Some carriers only allow one package per label. If you attempt to create a multi-pac"""
    alternative_identifiers: Optional[list[AlternativeIdentifier]] = None
    """Additional information some carriers may provide by which to identify a given label in their system."""
    rate_details: Optional[list[dict[str, Any]]] = None
    tracking_url: Optional[str] = None
    """The URL to track the package. This URL is provided by the carrier and is unique to the tracking number."""
    ship_to: Optional[ShippingAddressTo] = None
    """The recipient's mailing address"""


class PartialShipmentForRateShopper(BaseModel):
    """
    Shipment information for Rate Shopper. Must NOT include carrier_id, service_code, or
    shipping_rule_id as Rate Shopper selects these automatically.
    """

    model_config = ConfigDict(populate_by_name=True)

    shipment_id: Optional[str] = None
    """A string that uniquely identifies the shipment"""
    requested_shipment_service: Optional[str] = None
    """The requested shipment service"""
    external_order_id: Optional[str] = None
    """ID that the Order Source assigned"""
    hold_until_date: Optional[datetime] = None
    """Date to hold the shipment until"""
    ship_by_date: Optional[datetime] = None
    """Date by which the shipment should be shipped"""
    retail_rate: Optional[MonetaryValue] = None
    """The retail rate for the shipment"""
    store_id: Optional[str] = None
    """The store ID associated with the shipment"""
    items: Optional[list[ShipmentItem]] = None
    """Describe the packages included in this shipment as related to potential metadata that was imported from external order s"""
    notes_from_buyer: Optional[str] = None
    """Notes from the buyer"""
    notes_for_gift: Optional[str] = None
    """Gift notes"""
    is_gift: Optional[bool] = None
    """Indicates if the shipment is a gift"""
    assigned_user: Optional[str] = None
    """User assigned to the shipment"""
    amount_paid: Optional[MonetaryValue] = None
    """Total amount paid for the order"""
    shipping_paid: Optional[MonetaryValue] = None
    """Amount paid for shipping"""
    tax_paid: Optional[MonetaryValue] = None
    """Amount paid for taxes"""
    zone: Optional[int] = None
    """Shipping zone"""
    display_scheme: Optional[str] = None
    """Display scheme for the shipment"""
    tax_identifiers: Optional[list[TaxIdentifier]] = None
    external_shipment_id: Optional[str] = None
    """A unique user-defined key to identify a shipment. This can be used to retrieve the shipment. > **Warning:** The `externa"""
    shipment_number: Optional[str] = None
    """A non-unique user-defined number used to identify a shipment. If undefined, this will match the external_shipment_id of """
    ship_date: Optional[str] = None
    """The date that the shipment was (or will be) shippped. ShipStation will take the day of week into consideration. For exam"""
    created_at: Optional[datetime] = None
    """The date and time that the shipment was created in ShipStation ."""
    modified_at: Optional[datetime] = None
    """The date and time that the shipment was created or last modified."""
    shipment_status: Optional[ShipmentStatus] = None
    """The current status of the shipment"""
    ship_to: Optional[ShippingAddressTo] = None
    """The recipient's mailing address"""
    ship_from: Optional[ShippingAddress] = None
    """The shipment's origin address. If you frequently ship from the same location, consider [creating a warehouse]. Then you """
    warehouse_id: Optional[str] = None
    """The [warehouse] that the shipment is being shipped from. Either `warehouse_id` or `ship_from` must be specified."""
    return_to: Optional[ShippingAddress] = None
    """The return address for this shipment. Defaults to the `ship_from` address. Can be sent with a warehouse_id, in which cas"""
    is_return: Optional[bool] = None
    """An optional indicator if the shipment is intended to be a return. Defaults to false if not provided."""
    confirmation: Optional[DeliveryConfirmation] = None
    """The type of delivery confirmation that is required for this shipment"""
    customs: Optional[InternationalShipmentOptions] = None
    """Customs information. This is usually only needed for international shipments."""
    advanced_options: Optional[AdvancedShipmentOptions] = None
    """Advanced shipment options. These are entirely optional."""
    insurance_provider: Optional[InsuranceProvider] = None
    """The insurance provider to use for any insured packages in the shipment."""
    tags: Optional[list[Tag]] = None
    """Arbitrary tags associated with this shipment. Tags can be used to categorize shipments, and shipments can be queried by """
    order_source_code: Optional[OrderSourceName] = None
    packages: Optional[list[Package]] = None
    """The packages in the shipment. > **Note:** Some carriers only allow one package per shipment. If you attempt to create a """
    total_weight: Optional[Weigth] = None
    """The combined weight of all packages in the shipment"""
    comparison_rate_type: Optional[str] = None
    """Calculate a rate for this shipment with the requested carrier using a ratecard that differs from the default. Only suppo"""


class CreateLabelRateShopperRequestBody(BaseModel):
    """Request body for creating a label using Rate Shopper"""

    model_config = ConfigDict(populate_by_name=True)

    shipment: PartialShipmentForRateShopper
    """Shipment details. Must NOT include carrier_id, service_code, or shipping_rule_id as Rate Shopper selects these automatic"""
    label_format: Optional[LabelFormat] = None
    label_layout: Optional[LabelLayout] = None
    display_scheme: Optional[DisplayScheme] = None
    label_download_type: Optional[str] = None
    """Specifies how the label should be downloaded. - url: Returns URLs to download the label - inline: Returns the label data"""


class CreateLabelRateShopperResponseBody(BaseModel):
    """Response from creating a label using Rate Shopper"""

    model_config = ConfigDict(populate_by_name=True)

    label_id: Optional[str] = None
    """A string that uniquely identifies the label. This ID is generated by ShipStation when the label is created."""
    status: Optional[LabelStatus] = None
    shipment_id: Optional[str] = None
    """The shipment that this label is for. ShipStation can create a shipment for you automatically when you [create a label], """
    external_shipment_id: Optional[str] = None
    """A unique user-defined key to identify a shipment. This can be used to retrieve the shipment. > **Warning:** The `externa"""
    external_order_id: Optional[str] = None
    """ID that the Order Source assigned"""
    shipment: Optional[Shipment] = None
    """The shipment information used to generate the label"""
    ship_date: Optional[str] = None
    """The date that the package was (or will be) shippped. ShipStation will take the day of week into consideration. For examp"""
    created_at: Optional[datetime] = None
    """The date and time that the label was created in ShipStation ."""
    shipment_cost: Optional[MonetaryValue] = None
    """The cost of shipping, delivery confirmation, and other carrier charges. This amount **does not** include insurance costs"""
    insurance_cost: Optional[MonetaryValue] = None
    """The insurance cost for this package. Add this to the `shipment_cost` field to get the total cost."""
    requested_comparison_amount: Optional[MonetaryValue] = None
    """The total shipping cost for the specified comparison_rate_type."""
    tracking_number: Optional[str] = None
    """The tracking number for the package. Tracking number formats vary across carriers."""
    is_return_label: Optional[bool] = None
    """Indicates whether this is a return label. You may also want to set the `rma_number` so you know what is being returned."""
    rma_number: Optional[str] = None
    """An optional Return Merchandise Authorization number. This field is useful for return labels. You can set it to any strin"""
    is_international: Optional[bool] = None
    """Indicates whether this is an international shipment. That is, the originating country and destination country are differ"""
    batch_id: Optional[str] = None
    """If this label was created as part of a [batch], then this is the unique ID of that batch."""
    carrier_id: Optional[str] = None
    """The unique ID of the [carrier account] that was used to create this label"""
    charge_event: Optional[LabelChargeEvent] = None
    """The label charge event."""
    outbound_label_id: Optional[str] = None
    """The `label_id` of the original (outgoing) label that the return label is for. This associates the two labels together, w"""
    service_code: Optional[str] = None
    """The [carrier service] used to ship the package, such as `fedex_ground`, `usps_first_class_mail`, `flat_rate_envelope`, e"""
    test_label: Optional[bool] = None
    """Indicate if this label is being used only for testing purposes. If true, then no charge will be added to your account."""
    package_code: Optional[str] = None
    """The [package type], such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc. The code `package` indicates """
    validate_address: Optional[ValidateAddress] = None
    voided: Optional[bool] = None
    """Indicates whether the label has been [voided]"""
    voided_at: Optional[datetime] = None
    """The date and time that the label was [voided] , or `null` if the label has not been voided"""
    label_download_type: Optional[LabelDownloadType] = None
    label_format: Optional[LabelFormat] = None
    """The file format that you want the label to be in. We recommend `pdf` format because it is supported by all carriers, whe"""
    display_scheme: Optional[DisplayScheme] = None
    """The display format that the label should be shown in."""
    label_layout: Optional[LabelLayout] = None
    """The layout (size) that you want the label to be in. The `label_format` determines which sizes are allowed. `4x6` is supp"""
    trackable: Optional[bool] = None
    """Indicates whether the shipment is trackable, in which case the `tracking_status` field will reflect the current status a"""
    label_image_id: Optional[str] = None
    """The label image resource that was used to create a custom label image."""
    carrier_code: Optional[str] = None
    """The [shipping carrier] who will ship the package, such as `fedex`, `dhl_express`, `stamps_com`, etc."""
    confirmation: Optional[DeliveryConfirmation] = None
    """The type of delivery confirmation that is required for this shipment."""
    tracking_status: Optional[TrackingStatus] = None
    """The current status of the package, such as `in_transit` or `delivered`"""
    label_download: Optional[LabelDownload] = None
    form_download: Optional[Link] = None
    """The link to download the customs form (a.k.a. commercial invoice) for this shipment, if any. Forms are in PDF format. Th"""
    qr_code_download: Optional[OptionalLink] = None
    """The QR code download for the package"""
    paperless_download: Optional[PaperlessDownload] = None
    """The paperless details which may contain elements like `href`, `instructions` and `handoff_code`."""
    insurance_claim: Optional[Link] = None
    """The link to submit an insurance claim for the shipment. This field is null if the shipment is not insured or if the insu"""
    packages: Optional[list[LabelPackage]] = None
    """The label's package(s). > **Note:** Some carriers only allow one package per label. If you attempt to create a multi-pac"""
    alternative_identifiers: Optional[list[AlternativeIdentifier]] = None
    """Additional information some carriers may provide by which to identify a given label in their system."""
    rate_details: Optional[list[dict[str, Any]]] = None
    tracking_url: Optional[str] = None
    """The URL to track the package. This URL is provided by the carrier and is unique to the tracking number."""
    ship_to: Optional[ShippingAddressTo] = None
    """The recipient's mailing address"""
    rate_shopper_id: Optional[str] = None
    """The Rate Shopper strategy used to create this label"""


class CreateLabelRequestBody(BaseModel):
    """A purchase label request body"""

    model_config = ConfigDict(populate_by_name=True)

    shipment: Shipment
    """The shipment information used to generate the label"""
    label_id: Optional[str] = None
    """A string that uniquely identifies the label. This ID is generated by ShipStation when the label is created."""
    status: Optional[LabelStatus] = None
    shipment_id: Optional[str] = None
    """The shipment that this label is for. ShipStation can create a shipment for you automatically when you [create a label], """
    external_shipment_id: Optional[str] = None
    """A unique user-defined key to identify a shipment. This can be used to retrieve the shipment. > **Warning:** The `externa"""
    external_order_id: Optional[str] = None
    """ID that the Order Source assigned"""
    ship_date: Optional[str] = None
    """The date that the package was (or will be) shippped. ShipStation will take the day of week into consideration. For examp"""
    created_at: Optional[datetime] = None
    """The date and time that the label was created in ShipStation ."""
    shipment_cost: Optional[MonetaryValue] = None
    """The cost of shipping, delivery confirmation, and other carrier charges. This amount **does not** include insurance costs"""
    insurance_cost: Optional[MonetaryValue] = None
    """The insurance cost for this package. Add this to the `shipment_cost` field to get the total cost."""
    requested_comparison_amount: Optional[MonetaryValue] = None
    """The total shipping cost for the specified comparison_rate_type."""
    tracking_number: Optional[str] = None
    """The tracking number for the package. Tracking number formats vary across carriers."""
    is_return_label: Optional[bool] = None
    """Indicates whether this is a return label. You may also want to set the `rma_number` so you know what is being returned."""
    rma_number: Optional[str] = None
    """An optional Return Merchandise Authorization number. This field is useful for return labels. You can set it to any strin"""
    is_international: Optional[bool] = None
    """Indicates whether this is an international shipment. That is, the originating country and destination country are differ"""
    batch_id: Optional[str] = None
    """If this label was created as part of a [batch], then this is the unique ID of that batch."""
    carrier_id: Optional[str] = None
    """The unique ID of the [carrier account] that was used to create this label"""
    charge_event: Optional[LabelChargeEvent] = None
    """The label charge event."""
    outbound_label_id: Optional[str] = None
    """The `label_id` of the original (outgoing) label that the return label is for. This associates the two labels together, w"""
    service_code: Optional[str] = None
    """The [carrier service] used to ship the package, such as `fedex_ground`, `usps_first_class_mail`, `flat_rate_envelope`, e"""
    test_label: Optional[bool] = None
    """Indicate if this label is being used only for testing purposes. If true, then no charge will be added to your account."""
    package_code: Optional[str] = None
    """The [package type], such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc. The code `package` indicates """
    validate_address: Optional[ValidateAddress] = None
    voided: Optional[bool] = None
    """Indicates whether the label has been [voided]"""
    voided_at: Optional[datetime] = None
    """The date and time that the label was [voided] , or `null` if the label has not been voided"""
    label_download_type: Optional[LabelDownloadType] = None
    label_format: Optional[LabelFormat] = None
    """The file format that you want the label to be in. We recommend `pdf` format because it is supported by all carriers, whe"""
    display_scheme: Optional[DisplayScheme] = None
    """The display format that the label should be shown in."""
    label_layout: Optional[LabelLayout] = None
    """The layout (size) that you want the label to be in. The `label_format` determines which sizes are allowed. `4x6` is supp"""
    trackable: Optional[bool] = None
    """Indicates whether the shipment is trackable, in which case the `tracking_status` field will reflect the current status a"""
    label_image_id: Optional[str] = None
    """The label image resource that was used to create a custom label image."""
    carrier_code: Optional[str] = None
    """The [shipping carrier] who will ship the package, such as `fedex`, `dhl_express`, `stamps_com`, etc."""
    confirmation: Optional[DeliveryConfirmation] = None
    """The type of delivery confirmation that is required for this shipment."""
    tracking_status: Optional[TrackingStatus] = None
    """The current status of the package, such as `in_transit` or `delivered`"""
    label_download: Optional[LabelDownload] = None
    form_download: Optional[Link] = None
    """The link to download the customs form (a.k.a. commercial invoice) for this shipment, if any. Forms are in PDF format. Th"""
    qr_code_download: Optional[OptionalLink] = None
    """The QR code download for the package"""
    paperless_download: Optional[PaperlessDownload] = None
    """The paperless details which may contain elements like `href`, `instructions` and `handoff_code`."""
    insurance_claim: Optional[Link] = None
    """The link to submit an insurance claim for the shipment. This field is null if the shipment is not insured or if the insu"""
    packages: Optional[list[LabelPackage]] = None
    """The label's package(s). > **Note:** Some carriers only allow one package per label. If you attempt to create a multi-pac"""
    alternative_identifiers: Optional[list[AlternativeIdentifier]] = None
    """Additional information some carriers may provide by which to identify a given label in their system."""
    rate_details: Optional[list[dict[str, Any]]] = None
    tracking_url: Optional[str] = None
    """The URL to track the package. This URL is provided by the carrier and is unique to the tracking number."""
    ship_to: Optional[ShippingAddressTo] = None
    """The recipient's mailing address"""
    ship_to_service_point_id: Optional[str] = None
    """A unique identifier for a carrier service point where the shipment will be delivered by the carrier. This will take prec"""
    ship_from_service_point_id: Optional[str] = None
    """A unique identifier for a carrier drop off point where a merchant plans to deliver packages. This will take precedence o"""


class CreateLabelResponseBody(BaseModel):
    """A create label response body"""

    model_config = ConfigDict(populate_by_name=True)

    label_id: str
    """A string that uniquely identifies the label. This ID is generated by ShipStation when the label is created."""
    status: LabelStatus
    shipment_id: str
    """The shipment that this label is for. ShipStation can create a shipment for you automatically when you [create a label], """
    ship_date: str
    """The date that the package was (or will be) shippped. ShipStation will take the day of week into consideration. For examp"""
    created_at: datetime
    """The date and time that the label was created in ShipStation ."""
    shipment_cost: MonetaryValue
    """The cost of shipping, delivery confirmation, and other carrier charges. This amount **does not** include insurance costs"""
    insurance_cost: MonetaryValue
    """The insurance cost for this package. Add this to the `shipment_cost` field to get the total cost."""
    tracking_number: str
    """The tracking number for the package. Tracking number formats vary across carriers."""
    is_return_label: bool
    """Indicates whether this is a return label. You may also want to set the `rma_number` so you know what is being returned."""
    rma_number: str
    """An optional Return Merchandise Authorization number. This field is useful for return labels. You can set it to any strin"""
    is_international: bool
    """Indicates whether this is an international shipment. That is, the originating country and destination country are differ"""
    batch_id: str
    """If this label was created as part of a [batch], then this is the unique ID of that batch."""
    carrier_id: str
    """The unique ID of the [carrier account] that was used to create this label"""
    charge_event: LabelChargeEvent
    """The label charge event."""
    service_code: str
    """The [carrier service] used to ship the package, such as `fedex_ground`, `usps_first_class_mail`, `flat_rate_envelope`, e"""
    package_code: str
    """The [package type], such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc. The code `package` indicates """
    voided: bool
    """Indicates whether the label has been [voided]"""
    voided_at: datetime
    """The date and time that the label was [voided] , or `null` if the label has not been voided"""
    label_format: LabelFormat
    """The file format that you want the label to be in. We recommend `pdf` format because it is supported by all carriers, whe"""
    display_scheme: DisplayScheme
    """The display format that the label should be shown in."""
    label_layout: LabelLayout
    """The layout (size) that you want the label to be in. The `label_format` determines which sizes are allowed. `4x6` is supp"""
    trackable: bool
    """Indicates whether the shipment is trackable, in which case the `tracking_status` field will reflect the current status a"""
    label_image_id: str
    """The label image resource that was used to create a custom label image."""
    carrier_code: str
    """The [shipping carrier] who will ship the package, such as `fedex`, `dhl_express`, `stamps_com`, etc."""
    tracking_status: TrackingStatus
    """The current status of the package, such as `in_transit` or `delivered`"""
    label_download: LabelDownload
    form_download: Link
    """The link to download the customs form (a.k.a. commercial invoice) for this shipment, if any. Forms are in PDF format. Th"""
    paperless_download: PaperlessDownload
    """The paperless details which may contain elements like `href`, `instructions` and `handoff_code`."""
    insurance_claim: Link
    """The link to submit an insurance claim for the shipment. This field is null if the shipment is not insured or if the insu"""
    packages: list[LabelPackage]
    """The label's package(s). > **Note:** Some carriers only allow one package per label. If you attempt to create a multi-pac"""
    rate_details: list[dict[str, Any]]
    external_shipment_id: Optional[str] = None
    """A unique user-defined key to identify a shipment. This can be used to retrieve the shipment. > **Warning:** The `externa"""
    external_order_id: Optional[str] = None
    """ID that the Order Source assigned"""
    shipment: Optional[Shipment] = None
    """The shipment information used to generate the label"""
    requested_comparison_amount: Optional[MonetaryValue] = None
    """The total shipping cost for the specified comparison_rate_type."""
    outbound_label_id: Optional[str] = None
    """The `label_id` of the original (outgoing) label that the return label is for. This associates the two labels together, w"""
    test_label: Optional[bool] = None
    """Indicate if this label is being used only for testing purposes. If true, then no charge will be added to your account."""
    validate_address: Optional[ValidateAddress] = None
    label_download_type: Optional[LabelDownloadType] = None
    confirmation: Optional[DeliveryConfirmation] = None
    """The type of delivery confirmation that is required for this shipment."""
    qr_code_download: Optional[OptionalLink] = None
    """The QR code download for the package"""
    alternative_identifiers: Optional[list[AlternativeIdentifier]] = None
    """Additional information some carriers may provide by which to identify a given label in their system."""
    tracking_url: Optional[str] = None
    """The URL to track the package. This URL is provided by the carrier and is unique to the tracking number."""
    ship_to: Optional[ShippingAddressTo] = None
    """The recipient's mailing address"""


class CreateReturnLabelRequestBody(BaseModel):
    """A create return label request body"""

    model_config = ConfigDict(populate_by_name=True)

    charge_event: Optional[LabelChargeEvent] = None
    """The label charge event."""
    label_layout: Optional[LabelLayout] = None
    """The layout (size) that you want the label to be in. The `label_format` determines which sizes are allowed. `4x6` is supp"""
    label_format: Optional[LabelFormat] = None
    """The file format that you want the label to be in. We recommend `pdf` format because it is supported by all carriers, whe"""
    label_download_type: Optional[LabelDownloadType] = None
    display_scheme: Optional[DisplayScheme] = None
    """The display format that the label should be shown in."""
    label_image_id: Optional[str] = None
    """The label image resource that was used to create a custom label image."""


class CreateReturnLabelResponseBody(BaseModel):
    """A create return label response body"""

    model_config = ConfigDict(populate_by_name=True)

    label_id: Optional[str] = None
    """A string that uniquely identifies the label. This ID is generated by ShipStation when the label is created."""
    status: Optional[LabelStatus] = None
    shipment_id: Optional[str] = None
    """The shipment that this label is for. ShipStation can create a shipment for you automatically when you [create a label], """
    external_shipment_id: Optional[str] = None
    """A unique user-defined key to identify a shipment. This can be used to retrieve the shipment. > **Warning:** The `externa"""
    external_order_id: Optional[str] = None
    """ID that the Order Source assigned"""
    shipment: Optional[Shipment] = None
    """The shipment information used to generate the label"""
    ship_date: Optional[str] = None
    """The date that the package was (or will be) shippped. ShipStation will take the day of week into consideration. For examp"""
    created_at: Optional[datetime] = None
    """The date and time that the label was created in ShipStation ."""
    shipment_cost: Optional[MonetaryValue] = None
    """The cost of shipping, delivery confirmation, and other carrier charges. This amount **does not** include insurance costs"""
    insurance_cost: Optional[MonetaryValue] = None
    """The insurance cost for this package. Add this to the `shipment_cost` field to get the total cost."""
    requested_comparison_amount: Optional[MonetaryValue] = None
    """The total shipping cost for the specified comparison_rate_type."""
    tracking_number: Optional[str] = None
    """The tracking number for the package. Tracking number formats vary across carriers."""
    is_return_label: Optional[bool] = None
    """Indicates whether this is a return label. You may also want to set the `rma_number` so you know what is being returned."""
    rma_number: Optional[str] = None
    """An optional Return Merchandise Authorization number. This field is useful for return labels. You can set it to any strin"""
    is_international: Optional[bool] = None
    """Indicates whether this is an international shipment. That is, the originating country and destination country are differ"""
    batch_id: Optional[str] = None
    """If this label was created as part of a [batch], then this is the unique ID of that batch."""
    carrier_id: Optional[str] = None
    """The unique ID of the [carrier account] that was used to create this label"""
    charge_event: Optional[LabelChargeEvent] = None
    """The label charge event."""
    outbound_label_id: Optional[str] = None
    """The `label_id` of the original (outgoing) label that the return label is for. This associates the two labels together, w"""
    service_code: Optional[str] = None
    """The [carrier service] used to ship the package, such as `fedex_ground`, `usps_first_class_mail`, `flat_rate_envelope`, e"""
    test_label: Optional[bool] = None
    """Indicate if this label is being used only for testing purposes. If true, then no charge will be added to your account."""
    package_code: Optional[str] = None
    """The [package type], such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc. The code `package` indicates """
    validate_address: Optional[ValidateAddress] = None
    voided: Optional[bool] = None
    """Indicates whether the label has been [voided]"""
    voided_at: Optional[datetime] = None
    """The date and time that the label was [voided] , or `null` if the label has not been voided"""
    label_download_type: Optional[LabelDownloadType] = None
    label_format: Optional[LabelFormat] = None
    """The file format that you want the label to be in. We recommend `pdf` format because it is supported by all carriers, whe"""
    display_scheme: Optional[DisplayScheme] = None
    """The display format that the label should be shown in."""
    label_layout: Optional[LabelLayout] = None
    """The layout (size) that you want the label to be in. The `label_format` determines which sizes are allowed. `4x6` is supp"""
    trackable: Optional[bool] = None
    """Indicates whether the shipment is trackable, in which case the `tracking_status` field will reflect the current status a"""
    label_image_id: Optional[str] = None
    """The label image resource that was used to create a custom label image."""
    carrier_code: Optional[str] = None
    """The [shipping carrier] who will ship the package, such as `fedex`, `dhl_express`, `stamps_com`, etc."""
    confirmation: Optional[DeliveryConfirmation] = None
    """The type of delivery confirmation that is required for this shipment."""
    tracking_status: Optional[TrackingStatus] = None
    """The current status of the package, such as `in_transit` or `delivered`"""
    label_download: Optional[LabelDownload] = None
    form_download: Optional[Link] = None
    """The link to download the customs form (a.k.a. commercial invoice) for this shipment, if any. Forms are in PDF format. Th"""
    qr_code_download: Optional[OptionalLink] = None
    """The QR code download for the package"""
    paperless_download: Optional[PaperlessDownload] = None
    """The paperless details which may contain elements like `href`, `instructions` and `handoff_code`."""
    insurance_claim: Optional[Link] = None
    """The link to submit an insurance claim for the shipment. This field is null if the shipment is not insured or if the insu"""
    packages: Optional[list[LabelPackage]] = None
    """The label's package(s). > **Note:** Some carriers only allow one package per label. If you attempt to create a multi-pac"""
    alternative_identifiers: Optional[list[AlternativeIdentifier]] = None
    """Additional information some carriers may provide by which to identify a given label in their system."""
    rate_details: Optional[list[dict[str, Any]]] = None
    tracking_url: Optional[str] = None
    """The URL to track the package. This URL is provided by the carrier and is unique to the tracking number."""
    ship_to: Optional[ShippingAddressTo] = None
    """The recipient's mailing address"""


class GetLabelByIdResponseBody(BaseModel):
    """A get label by id response body"""

    model_config = ConfigDict(populate_by_name=True)

    label_id: Optional[str] = None
    """A string that uniquely identifies the label. This ID is generated by ShipStation when the label is created."""
    status: Optional[LabelStatus] = None
    shipment_id: Optional[str] = None
    """The shipment that this label is for. ShipStation can create a shipment for you automatically when you [create a label], """
    external_shipment_id: Optional[str] = None
    """A unique user-defined key to identify a shipment. This can be used to retrieve the shipment. > **Warning:** The `externa"""
    external_order_id: Optional[str] = None
    """ID that the Order Source assigned"""
    shipment: Optional[Shipment] = None
    """The shipment information used to generate the label"""
    ship_date: Optional[str] = None
    """The date that the package was (or will be) shippped. ShipStation will take the day of week into consideration. For examp"""
    created_at: Optional[datetime] = None
    """The date and time that the label was created in ShipStation ."""
    shipment_cost: Optional[MonetaryValue] = None
    """The cost of shipping, delivery confirmation, and other carrier charges. This amount **does not** include insurance costs"""
    insurance_cost: Optional[MonetaryValue] = None
    """The insurance cost for this package. Add this to the `shipment_cost` field to get the total cost."""
    requested_comparison_amount: Optional[MonetaryValue] = None
    """The total shipping cost for the specified comparison_rate_type."""
    tracking_number: Optional[str] = None
    """The tracking number for the package. Tracking number formats vary across carriers."""
    is_return_label: Optional[bool] = None
    """Indicates whether this is a return label. You may also want to set the `rma_number` so you know what is being returned."""
    rma_number: Optional[str] = None
    """An optional Return Merchandise Authorization number. This field is useful for return labels. You can set it to any strin"""
    is_international: Optional[bool] = None
    """Indicates whether this is an international shipment. That is, the originating country and destination country are differ"""
    batch_id: Optional[str] = None
    """If this label was created as part of a [batch], then this is the unique ID of that batch."""
    carrier_id: Optional[str] = None
    """The unique ID of the [carrier account] that was used to create this label"""
    charge_event: Optional[LabelChargeEvent] = None
    """The label charge event."""
    outbound_label_id: Optional[str] = None
    """The `label_id` of the original (outgoing) label that the return label is for. This associates the two labels together, w"""
    service_code: Optional[str] = None
    """The [carrier service] used to ship the package, such as `fedex_ground`, `usps_first_class_mail`, `flat_rate_envelope`, e"""
    test_label: Optional[bool] = None
    """Indicate if this label is being used only for testing purposes. If true, then no charge will be added to your account."""
    package_code: Optional[str] = None
    """The [package type], such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc. The code `package` indicates """
    validate_address: Optional[ValidateAddress] = None
    voided: Optional[bool] = None
    """Indicates whether the label has been [voided]"""
    voided_at: Optional[datetime] = None
    """The date and time that the label was [voided] , or `null` if the label has not been voided"""
    label_download_type: Optional[LabelDownloadType] = None
    label_format: Optional[LabelFormat] = None
    """The file format that you want the label to be in. We recommend `pdf` format because it is supported by all carriers, whe"""
    display_scheme: Optional[DisplayScheme] = None
    """The display format that the label should be shown in."""
    label_layout: Optional[LabelLayout] = None
    """The layout (size) that you want the label to be in. The `label_format` determines which sizes are allowed. `4x6` is supp"""
    trackable: Optional[bool] = None
    """Indicates whether the shipment is trackable, in which case the `tracking_status` field will reflect the current status a"""
    label_image_id: Optional[str] = None
    """The label image resource that was used to create a custom label image."""
    carrier_code: Optional[str] = None
    """The [shipping carrier] who will ship the package, such as `fedex`, `dhl_express`, `stamps_com`, etc."""
    confirmation: Optional[DeliveryConfirmation] = None
    """The type of delivery confirmation that is required for this shipment."""
    tracking_status: Optional[TrackingStatus] = None
    """The current status of the package, such as `in_transit` or `delivered`"""
    label_download: Optional[LabelDownload] = None
    form_download: Optional[Link] = None
    """The link to download the customs form (a.k.a. commercial invoice) for this shipment, if any. Forms are in PDF format. Th"""
    qr_code_download: Optional[OptionalLink] = None
    """The QR code download for the package"""
    paperless_download: Optional[PaperlessDownload] = None
    """The paperless details which may contain elements like `href`, `instructions` and `handoff_code`."""
    insurance_claim: Optional[Link] = None
    """The link to submit an insurance claim for the shipment. This field is null if the shipment is not insured or if the insu"""
    packages: Optional[list[LabelPackage]] = None
    """The label's package(s). > **Note:** Some carriers only allow one package per label. If you attempt to create a multi-pac"""
    alternative_identifiers: Optional[list[AlternativeIdentifier]] = None
    """Additional information some carriers may provide by which to identify a given label in their system."""
    rate_details: Optional[list[dict[str, Any]]] = None
    tracking_url: Optional[str] = None
    """The URL to track the package. This URL is provided by the carrier and is unique to the tracking number."""
    ship_to: Optional[ShippingAddressTo] = None
    """The recipient's mailing address"""


class GetTrackingLogFromLabelResponseBody(BaseModel):
    """A get tracking log from label response body"""

    model_config = ConfigDict(populate_by_name=True)

    tracking_number: str
    status_code: TrackingStatusDetailCode
    carrier_status_code: str
    """Carrier status code"""
    estimated_delivery_date: datetime
    events: list[dict[str, Any]]
    """The events that have occured during the lifetime of this tracking number."""
    tracking_url: Optional[str] = None
    """Carrier Tracking Url, if available"""
    status_detail_code: Optional[TrackingStatusDetailCode] = None
    carrier_code: Optional[str] = None
    carrier_id: Optional[int] = None
    """The unique ID of the [carrier account] that was used to create this label"""
    status_description: Optional[str] = None
    """Status description"""
    status_detail_description: Optional[str] = None
    """Status detail description"""
    carrier_detail_code: Optional[str] = None
    """Carrier detail code"""
    carrier_status_description: Optional[str] = None
    """carrier status description"""
    ship_date: Optional[datetime] = None
    actual_delivery_date: Optional[datetime] = None
    exception_description: Optional[str] = None
    """Exception description"""


class Label(BaseModel):
    """
    A label represents the physical sticker that you affix to a package to ship it.
    ShipStation makes it easy for you to [create labels] and then download them in PDF, PNG,
    or ZPL format so you can print them.
    """

    model_config = ConfigDict(populate_by_name=True)

    label_id: Optional[str] = None
    """A string that uniquely identifies the label. This ID is generated by ShipStation when the label is created."""
    status: Optional[LabelStatus] = None
    shipment_id: Optional[str] = None
    """The shipment that this label is for. ShipStation can create a shipment for you automatically when you [create a label], """
    external_shipment_id: Optional[str] = None
    """A unique user-defined key to identify a shipment. This can be used to retrieve the shipment. > **Warning:** The `externa"""
    external_order_id: Optional[str] = None
    """ID that the Order Source assigned"""
    shipment: Optional[Shipment] = None
    """The shipment information used to generate the label"""
    ship_date: Optional[str] = None
    """The date that the package was (or will be) shippped. ShipStation will take the day of week into consideration. For examp"""
    created_at: Optional[datetime] = None
    """The date and time that the label was created in ShipStation ."""
    shipment_cost: Optional[MonetaryValue] = None
    """The cost of shipping, delivery confirmation, and other carrier charges. This amount **does not** include insurance costs"""
    insurance_cost: Optional[MonetaryValue] = None
    """The insurance cost for this package. Add this to the `shipment_cost` field to get the total cost."""
    requested_comparison_amount: Optional[MonetaryValue] = None
    """The total shipping cost for the specified comparison_rate_type."""
    tracking_number: Optional[str] = None
    """The tracking number for the package. Tracking number formats vary across carriers."""
    is_return_label: Optional[bool] = None
    """Indicates whether this is a return label. You may also want to set the `rma_number` so you know what is being returned."""
    rma_number: Optional[str] = None
    """An optional Return Merchandise Authorization number. This field is useful for return labels. You can set it to any strin"""
    is_international: Optional[bool] = None
    """Indicates whether this is an international shipment. That is, the originating country and destination country are differ"""
    batch_id: Optional[str] = None
    """If this label was created as part of a [batch], then this is the unique ID of that batch."""
    carrier_id: Optional[str] = None
    """The unique ID of the [carrier account] that was used to create this label"""
    charge_event: Optional[LabelChargeEvent] = None
    """The label charge event."""
    outbound_label_id: Optional[str] = None
    """The `label_id` of the original (outgoing) label that the return label is for. This associates the two labels together, w"""
    service_code: Optional[str] = None
    """The [carrier service] used to ship the package, such as `fedex_ground`, `usps_first_class_mail`, `flat_rate_envelope`, e"""
    test_label: Optional[bool] = None
    """Indicate if this label is being used only for testing purposes. If true, then no charge will be added to your account."""
    package_code: Optional[str] = None
    """The [package type], such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc. The code `package` indicates """
    validate_address: Optional[ValidateAddress] = None
    voided: Optional[bool] = None
    """Indicates whether the label has been [voided]"""
    voided_at: Optional[datetime] = None
    """The date and time that the label was [voided] , or `null` if the label has not been voided"""
    label_download_type: Optional[LabelDownloadType] = None
    label_format: Optional[LabelFormat] = None
    """The file format that you want the label to be in. We recommend `pdf` format because it is supported by all carriers, whe"""
    display_scheme: Optional[DisplayScheme] = None
    """The display format that the label should be shown in."""
    label_layout: Optional[LabelLayout] = None
    """The layout (size) that you want the label to be in. The `label_format` determines which sizes are allowed. `4x6` is supp"""
    trackable: Optional[bool] = None
    """Indicates whether the shipment is trackable, in which case the `tracking_status` field will reflect the current status a"""
    label_image_id: Optional[str] = None
    """The label image resource that was used to create a custom label image."""
    carrier_code: Optional[str] = None
    """The [shipping carrier] who will ship the package, such as `fedex`, `dhl_express`, `stamps_com`, etc."""
    confirmation: Optional[DeliveryConfirmation] = None
    """The type of delivery confirmation that is required for this shipment."""
    tracking_status: Optional[TrackingStatus] = None
    """The current status of the package, such as `in_transit` or `delivered`"""
    label_download: Optional[LabelDownload] = None
    form_download: Optional[Link] = None
    """The link to download the customs form (a.k.a. commercial invoice) for this shipment, if any. Forms are in PDF format. Th"""
    qr_code_download: Optional[OptionalLink] = None
    """The QR code download for the package"""
    paperless_download: Optional[PaperlessDownload] = None
    """The paperless details which may contain elements like `href`, `instructions` and `handoff_code`."""
    insurance_claim: Optional[Link] = None
    """The link to submit an insurance claim for the shipment. This field is null if the shipment is not insured or if the insu"""
    packages: Optional[list[LabelPackage]] = None
    """The label's package(s). > **Note:** Some carriers only allow one package per label. If you attempt to create a multi-pac"""
    alternative_identifiers: Optional[list[AlternativeIdentifier]] = None
    """Additional information some carriers may provide by which to identify a given label in their system."""
    rate_details: Optional[list[dict[str, Any]]] = None
    tracking_url: Optional[str] = None
    """The URL to track the package. This URL is provided by the carrier and is unique to the tracking number."""
    ship_to: Optional[ShippingAddressTo] = None
    """The recipient's mailing address"""


class ListLabelsResponseBody(BaseModel):
    """A list label response body"""

    model_config = ConfigDict(populate_by_name=True)

    total: int
    """The total number of items across all pages of results"""
    page: int
    """The current page number of results. For example, if there are 80 results, and the page size is 25, then `page` could be """
    pages: int
    """The total number of pages of results. For example, if there are 80 results, and the page size is 25, then `pages` would """
    links: PaginationLink
    labels: list[Label]
    """The labels that matched the query criteria. If no matching labels were found, then this array is empty; otherwise, it co"""


class VoidLabelResponseBody(BaseModel):
    """A void label response body"""

    model_config = ConfigDict(populate_by_name=True)

    approved: bool
    """Indicates whether the attempt to void the label was successful"""
    message: str
    reason_code: Optional[LabelVoidFailureReason] = None
    """Indicates a normalized reason for the conditions if the void attempt was not approved. Will not populate if approved is """
